nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']  # L'origine de votre client React
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':  # Applique CORS Ã  toutes les routes
            allow_origin: ['http://localhost:3000']  # L'origine de votre client React
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
